/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmobilfauzi;
//Muhammad Fauzi Purwanto
//19630627
/**
 *
 * @author USER
 */
import static com.sun.webkit.perf.WCFontPerfLogger.reset;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class Form_Transaksi extends javax.swing.JFrame {
    
    public String merek1;
    public long harga1;
    int bayar;
    public String tgl_minjam, tgl_kembali;
    private final database database = new database();
    private boolean databaru;
    ResultSet rsTransaksi = null;
    DefaultTableModel model;
   
    
   
    /**
     * Creates new form Form_Transaksi
     */
      
    public Form_Transaksi() {
       
        initComponents();
        data_nama();
        tampilkan();
        databaru = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        merek = new javax.swing.JComboBox<>();
        txtNoTransaksi = new javax.swing.JTextField();
        txtLamaSewa = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btn_hitung = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel3 = new javax.swing.JTable();
        btn_update = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cm_nama = new javax.swing.JComboBox<>();
        dateMinjam = new com.toedter.calendar.JDateChooser();
        dateKembali = new com.toedter.calendar.JDateChooser();
        CariData = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Merek");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("No Transaksi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 14, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Lama Sewa");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Harga");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Total");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        merek.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        merek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Merek Mobil", "HONDA", "AVANZA", "KIJANG" }));
        merek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merekActionPerformed(evt);
            }
        });
        jPanel1.add(merek, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 522, 30));

        txtNoTransaksi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtNoTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 522, -1));

        txtLamaSewa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtLamaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 482, -1));

        txtHarga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 521, -1));

        txtTotal.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 414, -1));

        btn_hitung.setBackground(new java.awt.Color(255, 153, 153));
        btn_hitung.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 89, -1));

        btn_simpan.setBackground(new java.awt.Color(102, 255, 153));
        btn_simpan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 89, 37));

        btn_kembali.setBackground(new java.awt.Color(204, 51, 255));
        btn_kembali.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 91, 40));

        btn_keluar.setBackground(new java.awt.Color(255, 255, 51));
        btn_keluar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 80, 37));

        tabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tabel3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 780, 124));

        btn_update.setBackground(new java.awt.Color(255, 51, 51));
        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 85, 37));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("/ HARI");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        btn_cetak.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_cetak.setText("CETAK NOTA");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 770, 30));

        btn_hapus.setBackground(new java.awt.Color(102, 255, 255));
        btn_hapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 83, 37));

        btn_reset.setBackground(new java.awt.Color(102, 255, 102));
        btn_reset.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 78, 39));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Tanggal Minjam");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Tanggal Kembali");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Nama Peminjam");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        cm_nama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cm_nama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel1.add(cm_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 520, 30));

        dateMinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateMinjamPropertyChange(evt);
            }
        });
        jPanel1.add(dateMinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 520, -1));

        dateKembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateKembaliPropertyChange(evt);
            }
        });
        jPanel1.add(dateKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 520, -1));

        CariData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CariDataKeyReleased(evt);
            }
        });
        jPanel1.add(CariData, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 520, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("Cari Data");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 204, 0));

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 1, 24)); // NOI18N
        jLabel1.setText("INPUTAN TRANSAKSI PENYEWA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        
        if (databaru) {        
         try {
           String sql = "insert into transaksi values('"
                   +txtNoTransaksi.getText()+"','"
                   +txtLamaSewa.getText()+"','"
                   +tgl_minjam+"','"
                   +tgl_kembali+"','"
                   +cm_nama.getSelectedItem()+"','"
                   +txtHarga.getText()+"','"
                   +merek.getSelectedItem()+"','"
                   +txtTotal.getText()+"')";
           Connection con = database.getConnection();
           PreparedStatement pst = con.prepareStatement(sql);
           pst.execute();
           JOptionPane.showMessageDialog(null, "Berhasil di Simpan");
           tampilkan();
           reset();
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Gagal di Simpan" + ex);
           
        }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        
        int lamasewa = Integer.parseInt(txtLamaSewa.getText());
        int harga    = Integer.parseInt(txtHarga.getText());
        int bayar    = (harga*lamasewa);
        txtTotal.setText(Integer.toString(bayar));
 
      
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        this.hide();
        Form_Mobil kembali = new Form_Mobil();
        kembali.show();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int result= JOptionPane.showConfirmDialog(rootPane, "Apakah Anda Yakin Ingin Keluar");
        if (result== JOptionPane.YES_OPTION)
        {System.exit(0);
    }      
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void merekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merekActionPerformed
        // TODO add your handling code here:
          
          merek1= (String) merek.getSelectedItem();
         if ("HONDA".equals(merek1)) {
         harga1 = 50000;
        } else if ("AVANZA".equals(merek1)) {
          harga1 = 75000;
        } else if ("KIJANG".equals(merek1)) {
          harga1 = 25000;   
        }
        txtHarga.setText(String.valueOf(harga1));
    }//GEN-LAST:event_merekActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM transaksi WHERE no ='"+txtNoTransaksi.getText()+"'";
            Connection con = database.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.execute();
            
           JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
            
            clearData();
            tampilkan();
            
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Hapus" + ex);
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel3MouseClicked
        // TODO add your handling code here:
         try{
             databaru = false;
             
             int row = tabel3.getSelectedRow();
             String no = tabel3.getModel().getValueAt(row, 0).toString();
             
             Connection con = database.getConnection();
             String sql = "select * from transaksi where no = '"+no+"'";
             PreparedStatement pst = con.prepareStatement(sql);
             ResultSet rs = pst.executeQuery(sql);
             
             if (rs.next()) {
                 txtNoTransaksi.setText(rs.getString(1));
                 txtLamaSewa.setText(rs.getString(2));
                 dateMinjam.setDate(rs.getDate(3));
                 dateKembali.setDate(rs.getDate(4));
                 cm_nama.setSelectedItem(rs.getString(5));
                 txtHarga.setText(rs.getString(6));
                 merek.setSelectedItem(rs.getString(7));
                 txtTotal.setText(rs.getString(8));
             }
         } catch (SQLException ex) {
             Logger.getLogger(Form_Transaksi.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_tabel3MouseClicked

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        try {
           File namafile = new File("src/rentalmobilfauzi/laporan_transaksi.jasper");
           JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, database.getConnection());
           JasperViewer.viewReport(jp, false);
       } catch (JRException e) {
           JOptionPane.showMessageDialog(rootPane, e);
       }
       
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void dateMinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateMinjamPropertyChange
        // TODO add your handling code here:
        if (dateMinjam.getDate()!=null){
            SimpleDateFormat format =new SimpleDateFormat("yyyy-MM-dd");
            tgl_minjam =format.format (dateMinjam.getDate());
        }
    }//GEN-LAST:event_dateMinjamPropertyChange

    private void dateKembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateKembaliPropertyChange
        // TODO add your handling code here:
         if (dateKembali.getDate()!=null){
            SimpleDateFormat format =new SimpleDateFormat("yyyy-MM-dd");
            tgl_kembali =format.format (dateKembali.getDate());
        }
    }//GEN-LAST:event_dateKembaliPropertyChange

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
           try {
               Connection con = database.getConnection();
               String sql = "UPDATE transaksi SET lamasewa = '%s',tanggal_minjam ='%s',tanggal_pengembalian = '%s',nama_peminjam = '%s',harga ='%s',merek ='%s',total ='%s' WHERE no ='%s'";
                  
               sql = String.format(
                   sql,
                   txtLamaSewa.getText(),
                   tgl_minjam,
                   tgl_kembali,
                   cm_nama.getSelectedItem(),
                   txtHarga.getText(),
                   merek.getSelectedItem(),
                   txtTotal.getText(),
                   txtNoTransaksi.getText()
                       
               );
           PreparedStatement pst = con.prepareStatement(sql);
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Berhasil di Update");
           tampilkan();
           reset();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Gagal di Update" + e);
             System.out.println(e.getMessage());
           
        }
        
         
      
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        clearData();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void CariDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CariDataKeyReleased
        // TODO add your handling code here:
        String key =CariData.getText();
        System.out.println(key);
        
        if(key!=""){
            CariData(key);
   
        }else{
        tampilkan();
    
        }
    }//GEN-LAST:event_CariDataKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CariData;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cm_nama;
    private com.toedter.calendar.JDateChooser dateKembali;
    private com.toedter.calendar.JDateChooser dateMinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> merek;
    private javax.swing.JTable tabel3;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtLamaSewa;
    private javax.swing.JTextField txtNoTransaksi;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
    
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("No");
        tabel.addColumn("Lama Sewa");
        tabel.addColumn("Tanggal Minjam");
        tabel.addColumn("Tanggal Pengembalian");
        tabel.addColumn("Nama Peminjam");
        tabel.addColumn("Merek");
        tabel.addColumn("Harga");  
        tabel.addColumn("Total");
                    
        try {
            Connection con = database.getConnection();
            String sql = "SELECT * FROM transaksi";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while(rs.next()){
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8)});
              
            }
            tabel3.setModel(tabel);
        } catch (Exception ex) {
           
        }
    }
     private void cariData(String key){
       
    }
     
    public void data_nama(){
        try{
            Connection con = database.getConnection();
            String query = "SELECT * FROM penyewa";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while (rs.next()){
                cm_nama.addItem(rs.getString("nama"));                
            }
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
            
        } catch (SQLException e) {
    }

    
    }

    private void clearData() {
          
        txtNoTransaksi.setText("");
        txtLamaSewa.setText("");
        dateMinjam.setDate(null);
        dateKembali.setDate(null);
        cm_nama.setSelectedItem("");
        txtHarga.setText("");
        merek.setSelectedItem("");
        txtTotal.setText("");
           
    }
    
   private void CariData (String key){
        try{
            Object[] judul_kolom = {"No Transaksi", "Lama Sewa", "Tanggal Minjam", "Tanggal Kembali","Nama Peminjam", "Merek", "Harga", "Total"};
            model = new DefaultTableModel(null,judul_kolom);
            tabel3.setModel(model);
            
            Connection con= database.getConnection();
            Statement stt=con.createStatement();
            model.getDataVector().removeAllElements();
            
            rsTransaksi=stt.executeQuery("SELECT * from transaksi WHERE no LIKE '%"+key+"%' OR nama_peminjam LIKE '%"+key+"%'");  
            while(rsTransaksi.next()){
                Object[] data={
                    rsTransaksi.getString("no"),
                    rsTransaksi.getString("lamasewa"),
                    rsTransaksi.getString("tanggal_minjam"),
                    rsTransaksi.getString("tanggal_pengembalian"),
                    rsTransaksi.getString("nama_peminjam"),
                    rsTransaksi.getString("harga"),         
                    rsTransaksi.getString("merek"),
                    rsTransaksi.getString("total")     
                };
               model.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
}