/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalmobilfauzi;
//Muhammad Fauzi Purwanto
//19630627
/**
 *
 * @author USER
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Form_Mobil extends javax.swing.JFrame {
    
    public String nopol1;
    public String merek1;
    public long harga1;

    /**
     * Creates new form Form_Mobil
     */
        
    DefaultTableModel model;
    public Form_Mobil() {
        initComponents();
        String [] judul = {"No","Nopol","Merek","Harga","Tahun Keluar"};
        model =new DefaultTableModel(judul,0);
        tabel2.setModel(model);
        tampilkan();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        merek = new javax.swing.JComboBox<>();
        no = new javax.swing.JTextField();
        nopol = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        btn_sewa = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_kembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel2 = new javax.swing.JTable();
        btn_lanjut = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tahunkeluar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Merek Mobil");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 27, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("No Transaksi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 65, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("No Polisi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 101, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Harga");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 142, -1, -1));

        merek.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        merek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Merek Mobil", "HONDA", "AVANZA", "KIJANG", " " }));
        merek.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                merekItemStateChanged(evt);
            }
        });
        merek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merekActionPerformed(evt);
            }
        });
        jPanel1.add(merek, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 24, 502, -1));

        no.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 62, 502, -1));

        nopol.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(nopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 101, 502, -1));

        harga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 139, 502, -1));

        btn_sewa.setBackground(new java.awt.Color(255, 255, 102));
        btn_sewa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_sewa.setText("Sewa Mobil");
        btn_sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sewaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 214, -1, 38));

        btn_hapus.setBackground(new java.awt.Color(204, 102, 255));
        btn_hapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 214, 83, 38));

        btn_kembali.setBackground(new java.awt.Color(255, 204, 102));
        btn_kembali.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 214, 85, 38));

        tabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 284, 616, 121));

        btn_lanjut.setBackground(new java.awt.Color(255, 51, 204));
        btn_lanjut.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_lanjut.setText("Lanjut");
        btn_lanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lanjutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_lanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 214, 86, 38));

        btn_reset.setBackground(new java.awt.Color(0, 255, 153));
        btn_reset.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 214, 88, 38));

        btn_edit.setBackground(new java.awt.Color(204, 255, 0));
        btn_edit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 214, 89, 38));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Tahun Keluar");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 179, -1, -1));

        tahunkeluar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tahunkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 176, 502, -1));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 1, 24)); // NOI18N
        jLabel1.setText("INPUTAN DATA MOBIL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(263, 263, 263))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void btn_sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sewaActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/db_rentalmobil","root","");
            cn.createStatement().executeUpdate("insert into mobil values"+"('"+no.getText()+"','"+nopol.getText()+"','"+merek.getSelectedItem()+"','"+harga.getText()+"','"+tahunkeluar.getText()+"')");
            tampilkan();
            reset();
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Data Belum Di Isi !!");
           
        }
    }//GEN-LAST:event_btn_sewaActionPerformed

    private void merekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merekActionPerformed
        // TODO add your handling code here:
       merek1= (String) merek.getSelectedItem();
         if ("HONDA".equals(merek1)) {
         nopol1= "DA7878MR";
         harga1 = 50000;
        } else if ("AVANZA".equals(merek1)) {
          nopol1= "MA889SI";
          harga1 = 75000;
      
        } else if ("KIJANG".equals(merek1)) {
          nopol1= "KA009JI";
          harga1 = 25000;
          
        }
        nopol.setText(nopol1);
        harga.setText(String.valueOf(harga1));
                   
    }//GEN-LAST:event_merekActionPerformed

    private void merekItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_merekItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_merekItemStateChanged

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        int result= JOptionPane.showConfirmDialog(rootPane, "Apakah Anda Yakin Ingin Keluar");
        if (result== JOptionPane.YES_OPTION)
        {System.exit(0);
        
        
        }
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/db_rentalmobil","root","");
            cn.createStatement().executeUpdate("delete from mobil where no ='"+no.getText()+"'");
            tampilkan();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(Form_Penyewa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel2MouseClicked
        // TODO add your handling code here:
         int i = tabel2.getSelectedRow();
        
        if(i>-1){
            no.setText(model.getValueAt(i,0).toString());
            nopol.setText(model.getValueAt(i,1).toString());
            merek.setSelectedItem(model.getValueAt(i,2).toString());
            harga.setText(model.getValueAt(i,3).toString());
            tahunkeluar.setText(model.getValueAt(i,4).toString());
        }
        
    }//GEN-LAST:event_tabel2MouseClicked

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
         reset();
        
    }
        private void reset(){
        no.setText("");
        nopol.setText("");
        merek.setSelectedItem("");
        harga.setText("");
        tahunkeluar.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/db_rentalmobil","root","");
            cn.createStatement().executeUpdate("update mobil set nopol ='"+nopol.getText()+"',merek ='"+merek.getSelectedItem()+"',harga ='"+harga.getText()+"',tahunkeluar ='"+tahunkeluar.getText()+"' where no ='"+no.getText()+"'");
            tampilkan();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(Form_Penyewa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_lanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lanjutActionPerformed
        // TODO add your handling code here:
        this.hide();
        Form_Transaksi Lanjut = new Form_Transaksi();
        Lanjut.show();
    }//GEN-LAST:event_btn_lanjutActionPerformed

  
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Mobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_lanjut;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sewa;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> merek;
    private javax.swing.JTextField no;
    private javax.swing.JTextField nopol;
    private javax.swing.JTable tabel2;
    private javax.swing.JTextField tahunkeluar;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
        int row = tabel2.getRowCount();
        for(int a=0; a<row;a++){
            model.removeRow(0);
        }
      
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/db_rentalmobil","root","");
            ResultSet rs  = cn.createStatement().executeQuery("SELECT * FROM mobil");
            while(rs.next()){
                String data []= {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_Penyewa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

 }

